# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20161026_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('T', 'Technology'), ('A', 'Arts'), ('TA', 'Technology and Art')], default='T', max_length=2),
            preserve_default=False,
        ),
    ]
